// RepoMemory — ZIP export of generated context pack

import JSZip from 'jszip';
import type { GeneratedFile } from './types';

/** Create a ZIP buffer containing all generated files */
export async function createContextPackZip(files: GeneratedFile[]): Promise<Uint8Array> {
  const zip = new JSZip();

  for (const file of files) {
    zip.file(file.fileName, file.content);
  }

  // Add a README explaining how to use the pack
  zip.file(
    'README-REPOMEMORY.md',
    `# RepoMemory — Generated Context Pack

This pack was auto-generated by RepoMemory to improve your AI coding agent's context quality.

## Files Included

${files.map(f => `- **${f.fileName}** — ${getFileDescription(f.fileName)}`).join('\n')}

## Installation

1. Copy \`CLAUDE.md\` and \`.claudeignore\` to your project root
2. Copy the \`commands/\` folder to your project's \`.opencode/commands/\` or \`.claude/commands/\`
3. (Optional) Install the pre-commit hook: \`chmod +x hooks/pre-commit.sh && ln -s ../../hooks/pre-commit.sh .git/hooks/pre-commit\`

## Usage

- Open your project in Claude Code or OpenCode
- The agent will automatically read CLAUDE.md for project context
- Use slash commands: \`/review\`, \`/test\`, \`/deploy\`
- The pre-commit hook will remind you to keep context fresh
`
  );

  return await zip.generateAsync({ type: 'uint8array', compression: 'DEFLATE' });
}

function getFileDescription(fileName: string): string {
  switch (fileName) {
    case 'CLAUDE.md':
      return 'Main project context file — architecture, commands, conventions, testing, deployment';
    case '.claudeignore':
      return 'File exclusion rules for AI context scanning';
    case 'commands/review.md':
      return 'Slash command for code review workflow';
    case 'commands/test.md':
      return 'Slash command for running tests with context';
    case 'commands/deploy.md':
      return 'Slash command for deployment checklist';
    case 'hooks/pre-commit.sh':
      return 'Git pre-commit hook for context freshness reminder';
    default:
      return 'AI-generated context file';
  }
}
